@startuml prueba
!include .\\Atencion.puml
!include .\\Enfermero.puml
!include .\\IProfesional.puml
!include .\\Medico.puml
!include .\\Paciente.puml
!include .\\Persona.puml
!include .\\PrioridadTriage.puml
!include .\\Triage.puml
@enduml
